name: Local CI-CD Pipeline

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with: { python-version: '3.9' }
    - run: pip install -r requirements.txt
    - run: pytest

  build-and-push:
    name: Build and Push Docker Image
    runs-on: self-hosted
    needs: test
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/vijayeren30/my-devops-project:latest

  deploy:
    name: Deploy to Local Docker Swarm
    runs-on: self-hosted
    needs: build-and-push
    steps:
    - name: Deploy with Terraform
      run: |
        cd C:\Users\vijay\Devops_IA3\terraform
        terraform init
        terraform apply --auto-approve